#!/bin/sh

usage() {
	echo "Usage: dockerclear [OPTION]"
	echo "Try 'dockerclear --help' for more information."
}

help() {
	echo "dockerclear is used to stop/remove docker containers and images."
	printf "\nOptions:"
	printf "\n\t--stop, -s\tStop running containers"
	printf "\n\t--remove, -r\tRemove exited containers"
	printf "\n\t--clear, -c\tRemove images"
	printf "\n\t--all, -a\tExecute all other options\n\n"
	echo "Usage: dockerclear [OPTION]"
}

check() {
	command -v docker > /dev/null || { echo "'docker' must be installed" >&2; exit 1; }
}

stop() {
	check
	[ -z "$(docker ps -q)" ] || docker stop $(docker ps -q)
}

rm() {
	check
	[ -z "$(docker ps -f "status=exited" -q)" ] || docker rm $(docker ps -aq)
}

clear() {
	check
	[ -z "$(docker images -q)" ] || docker rmi $(docker images -q)
}

case "$1" in
	--help) help;;
	--stop|-s) stop;;
	--remove|-r) rm;;
	--clear|-c) clear;;
	--all|-a) stop; rm; clear;;
	*) usage;;
esac
